#!/bin/bash

./mx-basic &
modify="`stat mx-basic -c %y`"

while true; do
	sleep 1
	modify2="`stat mx-basic -c %y`"
	ps=`jobs -p`
	if [ "$modify2" != "$modify" ]; then
		kill -9 $ps #&> /dev/null
		wait $ps
		./mx-basic &
		modify="$modify2"
		echo
	fi
done
