#!/bin/bash

make &
modify="`stat mx.c -c %y`"

while true; do
	sleep 1
	modify2="`stat mx.c -c %y`"
	ps=`jobs -p`
	if [ "$modify2" != "$modify" ]; then
		kill -9 $ps &> /dev/null
		wait $ps
		make &
		modify="$modify2"
		echo
	fi
done
