#!/bin/bash

./sua &
modify="`stat sua -c %y`"

while true; do
	sleep 1
	modify2="`stat sua -c %y`"
	ps=`jobs -p`
	if [ "$modify2" != "$modify" ]; then
		kill -9 $ps &> /dev/null
		wait $ps
		./sua &
		modify="$modify2"
		echo
	fi
done
