#!/usr/bin/env perl

# su-a — гибкое тело, так звали в Древнем Шумере кошек

use common::sense;
use open qw/:std :utf8/;

use Term::ReadLine;
use Term::ANSIColor qw/colored RESET/;
use Carp;
$SIG{__DIE__} = sub { die($_[0] =~ /\n\z/? @_: Carp::confess(@_)) };
 

my $kon = Term::ReadLine::Gnu->new('SU-A');

my $sua = Sua::Ed->new;

my $MARKER = "🐈";
my $prompt = RESET . colored($MARKER, "cyan");


# Редактирование / https://tiswww.cwru.edu/php/chet/readline/readline.html
while ( defined (my $line = $kon->readline($prompt)) ) {

	next if $line =~ /^\s*$/;
	
	$sua->make($line);
}


# Командная строка
package Sua::Ed;

use Term::ANSIColor qw/colored/;

sub new {
	my $cls = shift;
	bless {
		INC => [".", "$::ENV{HOME}/.local/lib/sua"], 		# пути с исходниками
		open => undef,										# открытый оператор
		@_
	}, ref $cls || $cls;
}

# обрабатывает строку
sub make {
	my ($self, $line) = @_;
	
	my $rex = qr//;
	
	if($line =~ /^\d/) {	# строка
		print("Откройте файл командой ", colored("o", "red bold"), colored("pen", "blue bold"), " «оператор» «класс»\n"), return if !$self->{open};
		
	}
	elsif($line =~ /^\s*(o|open)\s+/) {
		
	}
	elsif($line =~ /^\s*(n|new)\s+(\S+)\s*$/) {
		my $x = $2;
		if($x =~ /^([a-z_]\w+)/)
		my $path = "src/";
		print "" if -e $path;
		open my $f, "<:utf8" or do { print "\n" };
	}
	elsif($line =~ /^\s*(l|list)\s+/) {
		
	}
	elsif($line =~ /^\s*(r|run)\s+/) {
		
	}
	elsif($line =~ /^\s*(b|rebase)\s+/) {
		
	}
	elsif($line =~ /^\s*(h|help|m|man)\s*$/) {
		print "
	${\colored($MARKER, 'green')}new swap¤¤ — создать метод
	${\colored($MARKER, 'white')}open swap¤¤ — открыть метод
	${\colored($MARKER, 'magenta')}open [-]% — открыть оператор
	${\colored($MARKER, 'green')}new [-]%4 — создать оператор с приоритетом 4
	${\colored($MARKER, 'yellow')}open % — открыть конструктор
	
	${\colored($MARKER, 'yellow')}inherit % from # — наследовать класс % от #

	${\colored($MARKER, 'blue bold')}list [1][-10] — список строк
	${\colored($MARKER, 'green')}10 — редактировать строку
";
	}
	else {
		print colored("?", "red"), "\n";
	}
}

# Компилирует файл или участок кода
package Sua::Compile;

use Term::ANSIColor qw/colored/;

sub new {
	my $cls = shift;
	bless {
		ed => undef,		# редактор
		file => undef, 		# файл который компилим. У консоли - undef
		code => undef,		# код
		to => undef,		# директория в которую компилим
		@_
	}, ref $cls || $cls;
}

sub compile {
	my ($self) = @_;
	
	$self->{prev} = 0;
	
	my $s = $self->{code} //= $self->rd;
	
	my @A;
	
	# лексика
	while($s =~ m{
		(?<dec> \d [\d_]* (\.\d [\d_]*)?) |
		(?<str> "(\\\\|\\"|[^\n])*") |
		
		(?<space> [\ \t]+) |
		(?<newline> \n)
	}gxn) {
		$self->error("не распознана лексема: `".substr($s, $self->{prev}, length($`))."`") if $self->{prev} != length($`);
		$self->{prev} = length($`) + length($&);
		
		if(exists $+{dec}) {
			my $s = $+{dec};
			$s =~ s/_//g;
			push @A, $s;
		}
	}
	
	$self->error("не распознана лексема: `".substr($s, $self->{prev})."`") if $self->{prev} != length($s);
	
	$self->wr(\@A);

	return 0;
}

# считываем файл
sub rd {
	my ($self) = @_;
	open my $f, "<:utf8", $self->{file} or $self->error("not open $self->{file}: $!");
	read $f, my $buf, -s $f;
	close $f;
	return $buf;
}

# записываем файл
sub wr {
	my ($self) = @_;
	open my $f, ">:utf8", $self->path2 or $self->error("not write $self->{path2}: $!");
	read $f, my $buf, -s $f;
	close $f;
	return $buf;
}

# путь скомпиленного файла
sub path2 {
	my ($self) = @_;
	$self->{path2} //= do {
		my $f = $self->{file} // "kon\$";
		$f =~ s!^.*([^/]*$)!$1!s;
		my $path = "$self->{to}/$f";
		
	}
}

# ошибка
sub error {
	my ($self, $s) = @_;
	die "$self->{file}:$self->{line}: $s\n";
}


1;